/**
 * nginxConfig.ts — Nginx configuration generation & safe writes (V8 / T5, Q2).
 *
 * Responsibilities:
 *  - `generateNginxConfig` fills the `__DOMAIN__` / `__PORT__` placeholders in
 *    the repo's nginx template.
 *  - `writeNginxConfig` writes ONLY to the white-listed nginx conf path
 *    (`SERVICE_NGINX_CONF_PATH`, default `/etc/nginx/conf.d/smart-cabinet.conf`).
 *    Arbitrary-path writes are refused — no path traversal, no free write.
 *  - `reloadNginx` runs `nginx -t` then `nginx -s reload` (both via execFile).
 *  - `restoreDefaultConfig` regenerates the active config from environment
 *    defaults (DEFAULT_SITE_DOMAIN / DEFAULT_SITE_PORT) and reloads.
 *
 * SECURITY: every external command goes through `runCommand` (execFile, no
 * shell). The writable path is fixed to a single white-listed location.
 */

import { readFileSync, writeFileSync } from 'fs';
import path from 'path';
import { runCommand, type CommandResult } from './runCommand';

/** Active nginx config path (locked white-list target). */
export const NGINX_CONF_PATH: string =
  process.env.SERVICE_NGINX_CONF_PATH || '/etc/nginx/conf.d/smart-cabinet.conf';

/**
 * Template source. At runtime the Next.js app runs from the project root
 * (dev) or `/var/www/smart-cabinet` (prod), so the committed template file is
 * reachable via `process.cwd()`. Override with `SERVICE_NGINX_TEMPLATE_PATH`.
 */
export const NGINX_TEMPLATE_PATH: string =
  process.env.SERVICE_NGINX_TEMPLATE_PATH ||
  path.join(process.cwd(), 'nginx-conf.d-smart-cabinet.conf');

/** Default domain/port used when restoring the built-in default config. */
const DEFAULT_DOMAIN: string = process.env.DEFAULT_SITE_DOMAIN || 'www.wstoolcabinet.com';
const DEFAULT_PORT: number =
  (() => {
    const n = parseInt(process.env.DEFAULT_SITE_PORT || '3000', 10);
    return Number.isFinite(n) ? n : 3000;
  })();

/** The ONLY paths `writeNginxConfig` is permitted to write to. */
const ALLOWED_WRITE_PATHS: ReadonlySet<string> = new Set<string>([NGINX_CONF_PATH]);

/** Options for generating a config from the template. */
export interface NginxGenerateOptions {
  domain: string;
  port: number;
  sslEmail?: string;
}

/** Aggregated result for reload / restore operations. */
export interface ReloadResult {
  ok: boolean;
  stdout: string;
  stderr: string;
  code: number;
}

/**
 * Fill the template's `__DOMAIN__` / `__PORT__` placeholders with real values.
 * The `sslEmail` is embedded as a comment so operators can see what was used.
 */
export function generateNginxConfig(opts: NginxGenerateOptions): string {
  const template = readFileSync(NGINX_TEMPLATE_PATH, 'utf8');
  const port = String(opts.port);
  const filled = template
    .split('__DOMAIN__')
    .join(String(opts.domain))
    .split('__PORT__')
    .join(port);

  // Append a provenance comment so the written file is self-describing.
  const emailLine = opts.sslEmail
    ? `# ssl email: ${opts.sslEmail}\n`
    : '';
  return `# Generated by smart-cabinet service manager\n# domain=${opts.domain} port=${port}\n${emailLine}${filled}`;
}

/** Whether a target path is permitted for writing. */
export function isWritePathAllowed(targetPath: string): boolean {
  return ALLOWED_WRITE_PATHS.has(targetPath);
}

/**
 * Write nginx config. Throws if the path is not in the white-list, so a
 * wrong/malicious path can never be written.
 */
export function writeNginxConfig(targetPath: string, content: string): void {
  if (!isWritePathAllowed(targetPath)) {
    throw new Error(
      `Refused to write to "${targetPath}". Only the white-listed path "${NGINX_CONF_PATH}" is permitted.`
    );
  }
  writeFileSync(targetPath, content, { mode: 0o644 });
}

/**
 * Run `nginx -t` then `nginx -s reload`. If the test fails, reload is skipped
 * and the failure is returned so the caller can surface it.
 */
export async function reloadNginx(): Promise<ReloadResult> {
  const parts: string[] = ['$ nginx -t'];
  const test: CommandResult = await runCommand('nginx', ['-t']);
  if (test.stdout) parts.push(test.stdout);
  if (test.stderr) parts.push(test.stderr);

  if (test.code !== 0) {
    parts.push(`exit code: ${test.code}`);
    return {
      ok: false,
      stdout: parts.join('\n'),
      stderr: '',
      code: test.code,
    };
  }

  const reload: CommandResult = await runCommand('nginx', ['-s', 'reload']);
  parts.push('\n$ nginx -s reload');
  if (reload.stdout) parts.push(reload.stdout);
  if (reload.stderr) parts.push(reload.stderr);
  parts.push(`exit code: ${reload.code}`);

  return {
    ok: reload.code === 0,
    stdout: parts.join('\n'),
    stderr: '',
    code: reload.code,
  };
}

/**
 * Restore the active config from the built-in default template (filled with
 * environment defaults) and reload nginx.
 */
export async function restoreDefaultConfig(): Promise<ReloadResult> {
  try {
    const content = generateNginxConfig({ domain: DEFAULT_DOMAIN, port: DEFAULT_PORT });
    writeNginxConfig(NGINX_CONF_PATH, content);
  } catch (err) {
    return {
      ok: false,
      stdout: `Failed to write default config: ${err instanceof Error ? err.message : String(err)}`,
      stderr: '',
      code: 1,
    };
  }
  return reloadNginx();
}
